# frozen_string_literal: true

require "jekyll"
require_relative "jekyll-aeo/version"
require_relative "jekyll-aeo/config"
require_relative "jekyll-aeo/utils/content_stripper"
require_relative "jekyll-aeo/utils/skip_logic"
require_relative "jekyll-aeo/utils/html_converter"
require_relative "jekyll-aeo/utils/md_url"
require_relative "jekyll-aeo/link_tag"
require_relative "jekyll-aeo/generators/markdown_page"
require_relative "jekyll-aeo/generators/llms_txt"
require_relative "jekyll-aeo/generators/url_map"
require_relative "jekyll-aeo/generators/domain_profile"
require_relative "jekyll-aeo/generators/robots_txt"
require_relative "jekyll-aeo/schema/faq_page"
require_relative "jekyll-aeo/schema/how_to"
require_relative "jekyll-aeo/schema/breadcrumb_list"
require_relative "jekyll-aeo/schema/organization"
require_relative "jekyll-aeo/schema/speakable"
require_relative "jekyll-aeo/schema/article"
require_relative "jekyll-aeo/tags/aeo_json_ld"
require_relative "jekyll-aeo/hooks"
require_relative "jekyll-aeo/commands/validate"
