# frozen_string_literal: true

require "test_helper"
require "tmpdir"
require "fileutils"

class UrlMapTest < Minitest::Test
  def setup
    @tmpdir = Dir.mktmpdir
    @source_dir = File.join(@tmpdir, "source")
    @dest_dir = File.join(@tmpdir, "public")
    FileUtils.mkdir_p(@source_dir)
    FileUtils.mkdir_p(@dest_dir)
  end

  def teardown
    FileUtils.rm_rf(@tmpdir)
  end

  def mock_collection(label)
    col = Object.new
    col.define_singleton_method(:label) { label }
    col
  end

  def mock_document(url:, collection_label:, source_file:, data: {}, dest_html: nil)
    dest_html ||= url.end_with?("/") ? "#{url}index.html" : "#{url}.html"
    d = { "title" => "", "layout" => "" }.merge(data)
    col = mock_collection(collection_label)
    src_dir = @source_dir
    dst_dir = @dest_dir
    path = File.join(src_dir, source_file)

    obj = Object.new
    obj.define_singleton_method(:data) { d }
    obj.define_singleton_method(:output_ext) { ".html" }
    obj.define_singleton_method(:url) { url }
    obj.define_singleton_method(:destination) { |_| File.join(dst_dir, dest_html) }
    obj.define_singleton_method(:collection) { col }
    obj.define_singleton_method(:path) { path }
    obj.define_singleton_method(:relative_path) { source_file }
    obj
  end

  def mock_page(url:, source_file:, data: {}, dest_html: nil)
    dest_html ||= url.end_with?("/") ? "#{url}index.html" : "#{url}.html"
    d = { "title" => "", "layout" => "" }.merge(data)
    dst_dir = @dest_dir

    obj = Object.new
    obj.define_singleton_method(:data) { d }
    obj.define_singleton_method(:output_ext) { ".html" }
    obj.define_singleton_method(:url) { url }
    obj.define_singleton_method(:destination) { |_| File.join(dst_dir, dest_html) }
    obj.define_singleton_method(:relative_path) { source_file }
    obj
  end

  def mock_site(documents: [], pages: [], aeo_config: { "url_map" => { "enabled" => true } })
    source = @source_dir
    dest = @dest_dir
    docs = documents
    pgs = pages

    site = Object.new
    site.define_singleton_method(:source) { source }
    site.define_singleton_method(:dest) { dest }
    site.define_singleton_method(:config) { { "jekyll_aeo" => aeo_config } }
    site.define_singleton_method(:documents) { docs }
    site.define_singleton_method(:pages) { pgs }
    site
  end

  def write_source(source_file)
    path = File.join(@source_dir, source_file)
    FileUtils.mkdir_p(File.dirname(path))
    File.write(path, "---\ntitle: Test\n---\nContent\n")
  end

  def output_path
    File.join(@source_dir, "docs/Url-Map.md")
  end

  # --- Enabled/Disabled tests ---

  def test_disabled_by_default
    site = mock_site(aeo_config: {})
    JekyllAeo::Generators::UrlMap.generate(site)

    refute_path_exists output_path
  end

  def test_disabled_via_master_switch
    site = mock_site(aeo_config: { "enabled" => false, "url_map" => { "enabled" => true } })
    JekyllAeo::Generators::UrlMap.generate(site)

    refute_path_exists output_path
  end

  def test_disabled_via_url_map_switch
    site = mock_site(aeo_config: { "url_map" => { "enabled" => false } })
    JekyllAeo::Generators::UrlMap.generate(site)

    refute_path_exists output_path
  end

  def test_generates_file_when_enabled
    write_source("about.md")
    page = mock_page(url: "/about/", source_file: "about.md", data: { "layout" => "page" })
    site = mock_site(pages: [page])
    JekyllAeo::Generators::UrlMap.generate(site)

    assert_path_exists output_path, "url-map.md should be created"
    content = File.read(output_path)

    assert content.start_with?("# Url Map\n")
  end

  def test_created_at_shown_by_default
    write_source("about.md")
    page = mock_page(url: "/about/", source_file: "about.md")
    site = mock_site(pages: [page])
    JekyllAeo::Generators::UrlMap.generate(site)

    content = File.read(output_path)

    assert_match(/Generated by Jekyll-AEO on \d{4}-\d{2}-\d{2} at \d{2}:\d{2}:\d{2}/, content)
  end

  def test_created_at_hidden_when_disabled
    write_source("about.md")
    page = mock_page(url: "/about/", source_file: "about.md")
    site = mock_site(pages: [page], aeo_config: {
                       "url_map" => { "enabled" => true, "show_created_at" => false }
                     })
    JekyllAeo::Generators::UrlMap.generate(site)

    content = File.read(output_path)

    refute_includes content, "Created by Jekyll-AEO Gem"
  end

  # --- Output path ---

  def test_output_relative_to_project_root_when_config_exists
    # Create a _config.yml in a parent dir to simulate project root != site.source
    project_root = @tmpdir
    File.write(File.join(project_root, "_config.yml"), "source: source\n")

    page = mock_page(url: "/about/", source_file: "about.md")
    write_source("about.md")
    site = mock_site(pages: [page])

    Dir.chdir(project_root) do
      JekyllAeo::Generators::UrlMap.generate(site)
    end

    expected_path = File.join(project_root, "docs/Url-Map.md")

    assert_path_exists expected_path, "url map should be written relative to project root"
  end

  def test_output_falls_back_to_source_without_config
    write_source("about.md")
    page = mock_page(url: "/about/", source_file: "about.md")
    site = mock_site(pages: [page])
    JekyllAeo::Generators::UrlMap.generate(site)

    assert_path_exists output_path, "url map should fall back to site.source"
  end

  def test_custom_output_file
    write_source("about.md")
    page = mock_page(url: "/about/", source_file: "about.md")
    site = mock_site(pages: [page], aeo_config: {
                       "url_map" => { "enabled" => true, "output_filepath" => "custom/map.md" }
                     })
    JekyllAeo::Generators::UrlMap.generate(site)

    custom_path = File.join(@source_dir, "custom/map.md")

    assert_path_exists custom_path, "custom output_file should work"
  end

  # --- Columns ---

  def test_all_columns_by_default
    write_source("about.md")
    page = mock_page(url: "/about/", source_file: "about.md", data: { "layout" => "page" })
    site = mock_site(pages: [page])
    JekyllAeo::Generators::UrlMap.generate(site)

    content = File.read(output_path)

    assert_includes content, "Layout"
    assert_includes content, "Url"
    assert_includes content, "Url DotMd"
    assert_includes content, "DotMd Mode"
    assert_includes content, "Excluded"
    assert_includes content, "Path"
    assert_includes content, "Page ID"
    assert_includes content, "Lang"
    assert_includes content, "Redirects"
  end

  def test_custom_columns
    write_source("about.md")
    page = mock_page(url: "/about/", source_file: "about.md", data: { "layout" => "page" })
    site = mock_site(pages: [page], aeo_config: {
                       "url_map" => { "enabled" => true, "columns" => %w[url path] }
                     })
    JekyllAeo::Generators::UrlMap.generate(site)

    content = File.read(output_path)

    assert_includes content, "| Url | Path |"
    refute_includes content, "Page ID"
    refute_includes content, "Url DotMd"
    refute_includes content, "Excluded"
  end

  # --- Sections ---

  def test_sections_grouped_by_collection
    write_source("_pages/about.md")
    write_source("_products/widget.md")

    doc1 = mock_document(url: "/about/", collection_label: "pages", source_file: "_pages/about.md")
    doc2 = mock_document(url: "/products/widget/", collection_label: "products", source_file: "_products/widget.md")
    site = mock_site(documents: [doc1, doc2])
    JekyllAeo::Generators::UrlMap.generate(site)

    content = File.read(output_path)

    assert_includes content, "## Pages"
    assert_includes content, "## Products"
  end

  def test_pages_section_first
    write_source("about.md")
    write_source("_posts/2024-01-01-hello.md")

    page = mock_page(url: "/about/", source_file: "about.md")
    doc = mock_document(url: "/blog/hello/", collection_label: "posts", source_file: "_posts/2024-01-01-hello.md")
    site = mock_site(documents: [doc], pages: [page])
    JekyllAeo::Generators::UrlMap.generate(site)

    content = File.read(output_path)
    pages_pos = content.index("## Pages")
    posts_pos = content.index("## Posts")

    assert_operator pages_pos, :<, posts_pos, "Pages section should come before Posts"
  end

  def test_items_sorted_by_url
    write_source("contact.md")
    write_source("about.md")

    page1 = mock_page(url: "/contact/", source_file: "contact.md")
    page2 = mock_page(url: "/about/", source_file: "about.md")
    site = mock_site(pages: [page1, page2])
    JekyllAeo::Generators::UrlMap.generate(site)

    content = File.read(output_path)
    about_pos = content.index("/about/")
    contact_pos = content.index("/contact/")

    assert_operator about_pos, :<, contact_pos, "Items should be sorted alphabetically by URL"
  end

  # --- Column values ---

  def test_page_id_and_lang_from_frontmatter
    write_source("about.md")
    page = mock_page(url: "/about/", source_file: "about.md", data: {
                       "page_id" => "about_page", "lang" => "en", "layout" => "page"
                     })
    site = mock_site(pages: [page])
    JekyllAeo::Generators::UrlMap.generate(site)

    content = File.read(output_path)

    assert_includes content, "about_page"
    assert_includes content, "en"
  end

  def test_redirect_from_displayed
    write_source("about.md")
    page = mock_page(url: "/about/", source_file: "about.md", data: {
                       "redirect_from" => ["/about-us/", "/old-about/"]
                     })
    site = mock_site(pages: [page])
    JekyllAeo::Generators::UrlMap.generate(site)

    content = File.read(output_path)

    assert_includes content, "/about-us/, /old-about/"
  end

  def test_url_dotmd_column
    write_source("about.md")
    page = mock_page(url: "/about/", source_file: "about.md")
    site = mock_site(pages: [page])
    JekyllAeo::Generators::UrlMap.generate(site)

    content = File.read(output_path)

    assert_includes content, "/about.md"
  end

  def test_skipped_pages_show_reason
    write_source("secret.md")
    page = mock_page(url: "/secret/", source_file: "secret.md", data: { "redirect_to" => "/other/" })
    site = mock_site(pages: [page])
    JekyllAeo::Generators::UrlMap.generate(site)

    content = File.read(output_path)

    assert_includes content, "redirect"
  end

  def test_skipped_page_has_empty_url_dotmd
    write_source("secret.md")
    page = mock_page(url: "/secret/", source_file: "secret.md", data: { "redirect_to" => "/other/" })
    site = mock_site(pages: [page])
    JekyllAeo::Generators::UrlMap.generate(site)

    content = File.read(output_path)
    lines = content.lines.select { |l| l.include?("/secret/") }

    assert_equal 1, lines.length
    # The url_dotmd cell should be empty for skipped pages
    cells = lines.first.split("|").map(&:strip)
    md_copy_index = 3 # 0=empty, 1=layout, 2=url, 3=url_dotmd

    assert_equal "", cells[md_copy_index]
  end

  # --- Edge cases ---

  def test_empty_site
    site = mock_site
    JekyllAeo::Generators::UrlMap.generate(site)

    content = File.read(output_path)

    assert content.start_with?("# Url Map\n")
    assert_match(/Generated by Jekyll-AEO on/, content)
    refute_includes content, "##"
  end

  def test_pipe_characters_escaped
    write_source("about.md")
    page = mock_page(url: "/about/", source_file: "about.md", data: {
                       "page_id" => "about|page", "layout" => "default"
                     })
    site = mock_site(pages: [page])
    JekyllAeo::Generators::UrlMap.generate(site)

    content = File.read(output_path)

    assert_includes content, 'about\|page'
  end

  def test_non_html_pages_excluded
    page_html = mock_page(url: "/about/", source_file: "about.md")
    write_source("about.md")

    page_css = Object.new
    page_css.define_singleton_method(:data) { {} }
    page_css.define_singleton_method(:output_ext) { ".css" }
    page_css.define_singleton_method(:url) { "/style.css" }
    page_css.define_singleton_method(:relative_path) { "style.css" }

    site = mock_site(pages: [page_html, page_css])
    JekyllAeo::Generators::UrlMap.generate(site)

    content = File.read(output_path)

    assert_includes content, "/about/"
    refute_includes content, "style.css"
  end

  def test_static_file_excluded
    obj = Jekyll::StaticFile.allocate
    obj.define_singleton_method(:url) { "/assets/logo/" }
    obj.define_singleton_method(:relative_path) { "_assets/logo.md" }
    obj.define_singleton_method(:output_ext) { ".html" }

    site = mock_site(documents: [obj])
    JekyllAeo::Generators::UrlMap.generate(site)

    content = File.read(output_path)

    refute_includes content, "logo"
  end

  # --- Bug fix: .html URLs produce correct url_dotmd ---

  def test_url_dotmd_for_html_url
    write_source("about.html")
    page = mock_page(url: "/about.html", source_file: "about.html", dest_html: "/about.html")
    site = mock_site(pages: [page])
    JekyllAeo::Generators::UrlMap.generate(site)

    content = File.read(output_path)

    assert_includes content, "/about.md"
    refute_includes content, "/about.html.md"
  end

  def test_url_dotmd_for_404_html
    write_source("404.html")
    page = mock_page(url: "/404.html", source_file: "404.html", dest_html: "/404.html")
    site = mock_site(pages: [page])
    JekyllAeo::Generators::UrlMap.generate(site)

    content = File.read(output_path)

    assert_includes content, "/404.md"
    refute_includes content, "/404.html.md"
  end

  # --- dotmd_mode column ---

  def test_dotmd_mode_column_shows_converter
    write_source("about.md")
    page = mock_page(url: "/about/", source_file: "about.md", data: {
                       "aeo_dotmd_mode" => "md2dotmd"
                     })
    site = mock_site(pages: [page], aeo_config: {
                       "url_map" => { "enabled" => true, "columns" => %w[url dotmd_mode] }
                     })
    JekyllAeo::Generators::UrlMap.generate(site)

    content = File.read(output_path)

    assert_includes content, "DotMd Mode"
    assert_includes content, "md2dotmd"
  end

  def test_dotmd_mode_column_in_default
    write_source("about.md")
    page = mock_page(url: "/about/", source_file: "about.md")
    site = mock_site(pages: [page])
    JekyllAeo::Generators::UrlMap.generate(site)

    content = File.read(output_path)

    assert_includes content, "DotMd Mode"
  end
end
