# frozen_string_literal: true

require "fileutils"

module JekyllAeo
  module Generators
    module UrlMap
      COLUMN_HEADERS = {
        "page_id" => "Page ID",
        "url" => "Url",
        "lang" => "Lang",
        "layout" => "Layout",
        "path" => "Path",
        "redirects" => "Redirects",
        "url_dotmd" => "Url DotMd",
        "excluded" => "Excluded",
        "dotmd_mode" => "DotMd Mode"
      }.freeze

      DEFAULT_COLUMNS = %w[layout url url_dotmd dotmd_mode excluded path page_id lang redirects].freeze

      def self.generate(site)
        config = JekyllAeo::Config.from_site(site)
        return if config["enabled"] == false

        url_map_config = config["url_map"] || {}
        return if url_map_config["enabled"] == false

        columns = url_map_config["columns"] || DEFAULT_COLUMNS
        items = collect_all_items(site, config, columns)
        sections = build_sections(items)
        markdown = build_markdown(sections, columns, url_map_config)

        root = project_root(site)
        output_file = File.join(root, url_map_config["output_filepath"] || "docs/Url-Map.md")
        unless File.expand_path(output_file).start_with?(File.expand_path(root))
          Jekyll.logger.error "AEO Url Map:", "output_filepath escapes project root — skipped"
          return
        end
        FileUtils.mkdir_p(File.dirname(output_file))
        File.write(output_file, markdown)
      end

      def self.collect_all_items(site, config, columns)
        items = []
        needs_excluded = columns.include?("excluded")
        needs_md = columns.include?("url_dotmd")
        needs_mode = columns.include?("dotmd_mode")
        baseurl = site.config["baseurl"].to_s.chomp("/")

        site.documents.each do |doc|
          next if doc.is_a?(Jekyll::StaticFile)
          next unless doc.output_ext == ".html"

          items << build_item(doc, doc.collection&.label, site, config, needs_excluded, needs_md, needs_mode, baseurl)
        end

        site.pages.each do |page|
          next if page.is_a?(Jekyll::StaticFile)
          next unless page.output_ext == ".html"

          items << build_item(page, nil, site, config, needs_excluded, needs_md, needs_mode, baseurl)
        end

        items
      end

      def self.build_item(obj, collection_label, site, config, needs_excluded, needs_md, needs_mode, baseurl = "")
        redirect_from = obj.data["redirect_from"]
        redirects_str = case redirect_from
                        when Array then redirect_from.join(", ")
                        when String then redirect_from
                        else ""
                        end

        item = {
          url: obj.url,
          page_id: obj.data["page_id"] || "",
          lang: obj.data["lang"] || "",
          layout: obj.data["layout"] || "",
          path: obj.relative_path,
          redirects: redirects_str,
          collection: collection_label
        }

        item[:excluded] = JekyllAeo::Utils::IncludeLogic.exclude_reason(obj, site, config) || "" if needs_excluded
        item[:url_dotmd] = md_url(obj.url, baseurl) if needs_md && (!needs_excluded || item[:excluded].empty?)
        item[:url_dotmd] ||= "" if needs_md
        item[:dotmd_mode] = obj.data["aeo_dotmd_mode"] || "" if needs_mode

        item
      end

      def self.build_sections(items)
        grouped = items.group_by { |item| item[:collection] }
        sections = []

        sections << { title: "Pages", items: grouped.delete(nil).sort_by { |i| i[:url] } } if grouped.key?(nil)

        sorted_keys = grouped.keys.compact.sort
        sorted_keys.each do |key|
          sections << { title: titleize(key), items: grouped[key].sort_by { |i| i[:url] } }
        end

        sections
      end

      def self.build_markdown(sections, columns, url_map_config)
        lines = []
        lines << "# Url Map"
        if url_map_config["show_created_at"] != false
          lines << "Generated by Jekyll-AEO on #{Time.now.strftime('%Y-%m-%d at %H:%M:%S')}"
        end
        lines << ""

        sections.each do |section|
          next if section[:items].empty?

          lines << "## #{section[:title]}"
          lines << ""
          lines << table_header(columns)
          lines << table_separator(columns)

          section[:items].each do |item|
            lines << table_row(item, columns)
          end

          lines << ""
        end

        "#{lines.join("\n").rstrip}\n"
      end

      def self.table_header(columns)
        cells = columns.map { |col| COLUMN_HEADERS[col] || col }
        "| #{cells.join(' | ')} |"
      end

      def self.table_separator(columns)
        cells = columns.map { |col| "-" * (COLUMN_HEADERS[col] || col).length }
        "| #{cells.join(' | ')} |"
      end

      def self.table_row(item, columns)
        cells = columns.map { |col| escape_pipe(item[col.to_sym].to_s) }
        "| #{cells.join(' | ')} |"
      end

      def self.escape_pipe(value)
        value.gsub("|", "\\|")
      end

      def self.md_url(url, baseurl = "")
        JekyllAeo::Utils::MdUrl.for(url, baseurl)
      end

      def self.titleize(label)
        case label
        when "posts"
          "Posts"
        else
          label.split(/[_-]/).map(&:capitalize).join(" ")
        end
      end

      def self.project_root(site)
        pwd = Dir.pwd
        if %w[_config.yml _config.yaml _config.toml].any? { |f| File.exist?(File.join(pwd, f)) }
          pwd
        else
          site.source
        end
      end

      private_class_method :collect_all_items, :build_item, :build_sections,
                           :build_markdown, :table_header, :table_separator,
                           :table_row, :escape_pipe, :md_url, :titleize,
                           :project_root
    end
  end
end
